### Create Account
# POST http://localhost:8080/api/create
# Content-Type: application/json

# {
#   "name": "Sabah",
#   "email": "sabah@example.com",
#   "mobileNumber": "1234567890"
# }


GET http://localhost:8080/api/fetch?mobileNumber=123456789
