# Create Account
# POST http://localhost:8080/api/create
# Content-Type: application/json

# {
#   "name": "Sabah",
#   "email": "sabah@example.com",
#   "mobileNumber": "1234567890"
# }

# Create Account
POST http://localhost:8080/api/create
Content-Type: application/json

{
  "name": "S",
  "email": "sabahexample.com",
  "mobileNumber": "12345670"
}

# Fetch Account
# GET http://localhost:8080/api/fetch?mobileNumber=1234567890

### Update Account
PUT http://localhost:8080/api/update
Content-Type: application/json

{
  "name": "Sabah",
  "email": "sabah.g@example.com",
  "mobileNumber": "1234567890",
  "accountsDTO": {
    "accountNumber": 1646532164,
    "accountType": "Current",
    "branchAddress": "99 Local Street, New Jersey"
  }
}

### Delete Account
DELETE http://localhost:8080/api/delete?mobileNumber=1234567890
